[test0, Y, 2]
SELECT to_char(now(), 'YYYYMMDD HH24MISS')

[test1, Y, 15:21:00]
select now()

[test2, Y, 5]
INSERT INTO db_monitor_history 
(
    threads_connected, threads_running, max_used_connections
)
SELECT 
    MAX(CASE WHEN VARIABLE_NAME = 'THREADS_CONNECTED' THEN VARIABLE_VALUE END) AS threads_connected,
    MAX(CASE WHEN VARIABLE_NAME = 'THREADS_RUNNING' THEN VARIABLE_VALUE END) AS threads_running,
    MAX(CASE WHEN VARIABLE_NAME = 'MAX_USED_CONNECTIONS' THEN VARIABLE_VALUE END) AS max_used_connections
FROM INFORMATION_SCHEMA.GLOBAL_STATUS
WHERE VARIABLE_NAME IN ('THREADS_CONNECTED', 'THREADS_RUNNING', 'MAX_USED_CONNECTIONS');

[test3, Y, 10]
INSERT INTO db_monitor_history 
(
    threads_connected, threads_running, max_used_connections
)
SELECT 
    MAX(CASE WHEN VARIABLE_NAME = 'THREADS_CONNECTED' THEN VARIABLE_VALUE END) AS threads_connected,
    MAX(CASE WHEN VARIABLE_NAME = 'THREADS_RUNNING' THEN VARIABLE_VALUE END) AS threads_running,
    MAX(CASE WHEN VARIABLE_NAME = 'MAX_USED_CONNECTIONS' THEN VARIABLE_VALUE END) AS max_used_connections
FROM INFORMATION_SCHEMA.GLOBAL_STATUS
WHERE VARIABLE_NAME IN ('THREADS_CONNECTED', 'THREADS_RUNNING', 'MAX_USED_CONNECTIONS');
